// Generated by CoffeeScript 1.6.3
var modules;

modules = require('../index')();

console.log(modules);

modules.hello();

console.log(modules.world);

module.exports = function() {
  return console.log("how interesting");
};
